### ISSUE TITLE
Use of POSTGRESQL instead of MariaDB

### ISSUE THREAD

**Issue by taaaahahaha** [discuitnet/discuit#101]
I havent been using go as a backend service and was wondering which configuration files should be changed to switch the database from mariadb to postgres.
I did import 
_ "github.com/lib/pq"
inside cli.go, but ./discuit migrate is taking a lot of time (The database creds are working and discuit database is created)

**Comment by Codycody31** [comment]
The Discuit codebase is built around MariaDB/MySQL, so it isn't meant to use PostgreSQL. for example:

https://github.com/discuitnet/discuit/blob/main/cli/migrate/migrate.go#L113-L134 

has `"mysql://` hardcoded, and while it may be possible it would require a large amount of altering in the codebase and migrations given they are for MySQL.

**Comment by taaaahahaha** [comment]
Yes, I know. I have updated the codebase to accept connections from postgres, however am running into issues when migrate is being ran.

**Comment by taaaahahaha** [comment]
It would need syntax altering in every sql query, as
the usage of the ? operator is supported in PostgreSQL, but it is not supported in MariaDB. The 
`mysql://`
and config changes gets the app running, and am able to create and work around a user. But for every functionality, the queries need to be altered.

Closing this issue, unless an ORM or standardized query mechanism between postgres and maria has been implemented
