### ISSUE TITLE
[Suggestion] Preview server

### ISSUE THREAD

**Issue by reallytiredofclowns** [discuitnet/discuit#120]
E.g., set up beta.discuit.net to preview features currently being coded, but not yet ready to be pushed to the live site.

Having a preview server like this would help to catch bugs and get early feedback before deploying to prod. You could even list a bunch of things to try for the community to help with testing. This would give the wider community more sense of ownership/involvement of the site. It also is ad-hoc evidence that site development is happening.

**Comment by Kaamkiya** [comment]
Relevant: https://discuit.net/AskDiscuit/post/mtaVWDhZ

So https://beta.discuit.net _does_ exist. Whatever is causing `*.discuit.net` to link to Discuit will have to be fixed first.

**Comment by previnder** [comment]
Fixed it. Don't exactly remember why, but at some point I'd added a wildcard DNS record to `discuit.net`, which was causing the problem. Also, beta.discuit.net is, at the moment, up and running.

Closing.
