### ISSUE TITLE
[Bug] Error when opening notifications (Unknown badge type "undefined")

### ISSUE THREAD

**Issue by TylerCode** [discuitnet/discuit#14]
Seems to be surrounding one user https://discuit.net/DiscuitMeta/post/wQ_o8X5N

Almost seems like they have a non existent badge assigned to them, but seems like the kind of error that requires peeking at the database. Here is the user profile: https://discuit.net/@asyoucanseE_

Here are the errors and some additional output:
![17aca35ac6c0c2c5384918e9](https://github.com/discuitnet/discuit/assets/18288340/953fb96e-15de-4b9d-8f8b-9f9d6fe3c908)
![qpwHtGv](https://github.com/discuitnet/discuit/assets/18288340/044e094b-d3aa-4876-9aa3-1c5d7c118e5a)
![Z7F2fm4](https://github.com/discuitnet/discuit/assets/18288340/1a6b3036-1b35-4ea2-aa82-003ec495f974)

**Comment by TylerCode** [comment]
Updated some verbiage, can still check [the post](https://discuit.net/DiscuitMeta/post/wQ_o8X5N) for more details. I can try to make a patch to handle undefined badges, but I probably won't have a lot of time for few days.

I also still think it would be worth checking the user `@asyoucanseE_` for any strangeness in the DB.

**Comment by previnder** [comment]
Thanks for the quick report, Tyler. Found the source of the bug: a missing `break` statement in a `switch` in JS. (This reminds me why it's a good thing that switch cases don't fall through in Go.)

**Comment by TylerCode** [comment]
Nice work on a quick fix! Out of curiosity, was there anything going on with `@asyoucanseE_`'s account? I thought it was strange that they seemed like the only one getting the error.

**Comment by previnder** [comment]
No doubt @asyoucanseE_  had a *"You're added as a moderator of X community"* notification in the inbox, which was the type of notification in the switch case that the `break` statement was missing (the `mod_add` notification type in 3cd64c0).
