### ISSUE TITLE
API: Communities endpoint returning duplicated data?

### ISSUE THREAD

**Issue by reallytiredofclowns** [discuitnet/discuit#17]
When I use the communities endpoint like so:

    https://discuit.net/api/communities?q=general

it returns a json object with two elements that are identical. Am I misunderstanding how the API is supposed to work?

**Comment by previnder** [comment]
Ideally, it should not return any duplicates (the SQL query for that endpoint needs a tiny little improvement). 

Although, I feel like I answered a different question from the one you intended. Could you elaborate what you meant a bit more?

**Comment by reallytiredofclowns** [comment]
No, I think you addressed my issue. I had expected the query to return a single element, and it seems you do too.

**Comment by previnder** [comment]
Just fixed this in 447f7b7, by the way.
