### ISSUE TITLE
Issue with Automatic Zoom on Input Fields on Mobile

### ISSUE THREAD

**Issue by fredrikburmester** [discuitnet/discuit#19]
Issue Overview:

While using on a mobile device, I’ve encountered an issue where the page automatically zooms in whenever I focus on an input field. This behavior disrupts the navigation and interaction with the site, especially when filling out forms.

Impact on Experience:

•	Layout Shift: The automatic zoom changes the expected layout, making it difficult to see the full form or other page elements without manually zooming out.
•	Accessibility and Usability: For users like myself, particularly those who may have difficulty with precise gestures, this unexpected zoom can make it challenging to interact with the site effectively.

Suspected Cause:

•	Font Size of Input Fields: It seems that the font size of input fields might be below the typical threshold that prevents mobile browsers from zooming in to enhance readability during text entry.

Suggested Solutions:

1.	Font Size Adjustment:
•	Increasing the font size for input, select, and textarea elements to at least 16px could potentially prevent this automatic zooming.
•	Advantages: This approach maintains the functionality of user-initiated zoom, preserving accessibility.
•	Considerations: Adjusting the font size may require minor design modifications to maintain a cohesive appearance.
2.	Viewport Meta Tag Usage:
•	An alternative could be to use a viewport meta tag with settings that limit user scaling. However, this could have broader implications on user experience and accessibility, which makes it less favorable.

**Comment by nickvanderwildt** [comment]
Ah, I'm glad you called this out, as I had the same issue. I specifically noticed it when I went back to my feed and realized all the content was cut off from being zoomed in. Very annoying behavior if you aren't tech-savvy and don't know you should pinch to zoom out.

I actually created a PR for the second solution: https://github.com/discuitnet/discuit/pull/20. This solution does not prevent users to zoom in and out themselves - do you reckon that still has implications on the user experience? I reckon when users are able to pinch to zoom themselves, it's not so much a hit on accessibility? But I'm curious to learn if that's not the case.

**Comment by fredrikburmester** [comment]
Thank you for sharing your solution and creating a PR. 

Apparently, since iOS 10, Apple made a change that prevents web developers from disabling user zooming. This means that the user-scalable=no parameter in the viewport meta tag no longer restricts users from zooming in or out on a webpage. 

Given this, this solution might not work for some devices. Another idea, which I've tested and seems to be working, is to target the font size of input fields directly. Specifically, we can use the @supports rule to target devices that support touch scrolling:

```
@supports (-webkit-overflow-scrolling: touch) {
  input, select, textarea {
    font-size: 16px; /* Ensuring the minimum font size to prevent zoom */
  }
}

```

Since this bumps the font size to something that might not work with the current design, some fields could look a bit weird. But it seems like a good solution.

**Comment by previnder** [comment]
Thanks for the detailed issue, @fredrikburmester. I merged @nickvanderwildt's PR and pushed a new update to the site. While the issue may have been solved, some folks are [not happy](https://discuit.net/DiscuitMeta/post/J6hI9THo) [with it](https://discuit.net/ShitPosting/post/gIXzKK_M).

I'm going to try your solution next, and also possibly make the ability to zoom a UI preference that can be enabled/disabled in the settings.

**Comment by nickvanderwildt** [comment]
I learned something today. I was not aware of the effect it would have on Android. Apologies to all the users affected!

**Comment by nickvanderwildt** [comment]
Perhaps worth considering, also with a11y in mind, is increasing --fs-normal to 1.6rem @previnder?

**Comment by previnder** [comment]
Increased the mobile font size to 16px in 349824e. It was probably a bit too small in anyway.
