### ISSUE TITLE
Error 1698: Can't Migrate or Serve Discuit

### ISSUE THREAD

**Issue by meneergroot** [discuitnet/discuit#23]
Hi there,

I'm testing Discuit on my Ubuntu NUC. I get an error that i don't have access as sudo or even as root.

i am currently root but i get ./discuit -migrate
2024/02/13 11:09:08 Error 1698: Access denied for user 'root'@'localhost'

ChatGPT states:
_If you are running a command as the root user, but the command itself is encountering an "Access denied" error, it means that the application or script is attempting to connect to MySQL using the 'root' user, and there may be an issue with the permissions for that user._

But where do i find this or add the correct setting? 
Playing around as a non-backend dev. 

Any help will be appreciated :)

**Comment by lydia-st** [comment]
Seems like Discuit can't read your configs! 

Have you written a `config.yaml`? If not, you can just copy `config.default.yaml` to `config.yaml`, then fill in the values there

**Comment by meneergroot** [comment]
Thanks a million. Took me 2 days to get my head around it. 
Mostly the problem i had that i was running  Ubuntu [Multipass](https://multipass.run/) on my Mac and i forgot to sudo -i and become root. Also i did a build.sh before cp config.default.yaml config.yaml

But with your helpful comment i finally got it up and running. 💯 

<img width="1207" alt="Screenshot 2024-02-15 at 20 36 33" src="https://github.com/discuitnet/discuit/assets/53813521/1a45756f-0f4f-411f-b61d-84dd838f269b">
