### ISSUE TITLE
Add DB Address & Port Fields to Configuration for compatability

### ISSUE THREAD

**Issue by Oracuda** [discuitnet/discuit#29]
https://github.com/discuitnet/discuit/blob/2831d6ea5ded8c77d6a7be0f07da59bd9f958549/main.go#L386
127.0.0.1 will not map to the host when running in a Docker container, also other situations.

**Comment by Oracuda** [comment]
Solved in https://github.com/discuitnet/discuit/pull/26

**Comment by previnder** [comment]
Merged #26.
