### ISSUE TITLE
The spacing/kerning issue in the menus

### ISSUE THREAD

**Issue by SmurfRepresentative** [discuitnet/discuit#35]
Hey everybody, hoping I did this correctly.

![5CA8DC04-FFEE-41EF-B043-DBFDEB962BE6](https://github.com/discuitnet/discuit/assets/160355261/7c898e03-81b4-406d-8866-74ffb8924cd9)
![F82ABE84-A2B9-493C-A92F-F7F5EAB85998](https://github.com/discuitnet/discuit/assets/160355261/62f69d68-b138-4b22-910e-1b657d149a09)

that is my current front page feed and the page when I clicked on the post where I replied on Discuit.

**Comment by SmurfRepresentative** [comment]
Was requested to add that I am using a 10.2” 9th gen ipad on new software whatever version that is.     

Thanks!

**Comment by Codycody31** [comment]
They also stated this way on a 10.2” 9th gen iPad
