### ISSUE TITLE
Deployment via OCI Containers

### ISSUE THREAD

**Issue by imbev** [discuitnet/discuit#4]
I suggest the addition of necessary Container/Compose files so that Docker, Podman, and Kubernetes can be used to deploy Discuit easily.

**Comment by imbev** [comment]
If you'd like help with this, let me know.

**Comment by previnder** [comment]
As it stands, this is not really necessary for the official instance (it's just a single server that's already deployed) but it might be useful for potential contributors. If you'd like to get this done, that'd be totally cool.

**Comment by previnder** [comment]
#37 closes this.
