### ISSUE TITLE
Voting element not updating when clicking on a discuit link

### ISSUE THREAD

**Issue by Mikezero0526** [discuitnet/discuit#43]
Click link circled in red.
<img width="731" alt="image" src="https://github.com/discuitnet/discuit/assets/44472582/c3c1ed47-0c12-41b7-a21e-d8d285bda485">

Old posts voting element still showing.
<img width="740" alt="image" src="https://github.com/discuitnet/discuit/assets/44472582/d569a954-d634-4b27-bb56-d88b92411740">

Refresh page to see correct element.
<img width="732" alt="image" src="https://github.com/discuitnet/discuit/assets/44472582/6d176773-3179-46ab-99e7-709f9262bbe6">

**Comment by monu-simon** [comment]
Hi Team, I would like to work on this bug.

**Comment by previnder** [comment]
Fixed in #84.
