### ISSUE TITLE
[Bug] Link post with non-accessible image results in 500 error

### ISSUE THREAD

**Issue by Codycody31** [discuitnet/discuit#66]
Initial post reporting this: https://discuit.net/DiscuitMeta/post/_FbRPTSe
Site link: https://www.mobilephonemuseum.com/
Image link: https://mpm-next.code8.link/logo.png (this image returns a 503 from apache, not an image)
Message on server when attempting to use URL: `500 Internal server error:  Unsupported image format`

Seems the image the site uses for its ogImage is not a format discuit supports. Or more like the [image](https://mpm-next.code8.link/logo.png) it is trying to use doesn't exist

https://github.com/discuitnet/discuit/blob/f6fc5b6aef8f224cf8b71551e430b4965921fb8c/core/post.go#L688-L730

**Comment by previnder** [comment]
Fixed in [dffb310](https://github.com/discuitnet/discuit/commit/dffb310a1b00ee8bbd8dc5f89baf2aa62bf16d5d)[dffb310](https://github.com/discuitnet/discuit/commit/dffb310a1b00ee8bbd8dc5f89baf2aa62bf16d5d)[dffb310](https://github.com/discuitnet/discuit/commit/dffb310a1b00ee8bbd8dc5f89baf2aa62bf16d5d)
