### ISSUE TITLE
Muted users still send a comment notification

### ISSUE THREAD

**Issue by reallytiredofclowns** [discuitnet/discuit#8]
As in the title. If an account is muted, I should not be notified that they commented to something I contributed.

E.g., I have [@autotldr](https://discuit.net/@autotldr) muted because I don't need to see a summary of things I read and posted myself. But I get comment notifications when it summarises my submissions.

**Comment by previnder** [comment]
Thanks for the bug report @reallytiredofclowns.

**Comment by Codycody31** [comment]
Maybe right around line 409 in `core/notification.go` we add something like this? I am not fully sure it would work as I don't fully understand how it works. In theory it will: get users muted by the person receiving the notification, loop through and check if a muted user matches the comment author, if so we halt here.

```go
// Check if the user who is receiving the notification hasn't muted the user if comment
if n.Type == NotificationTypeNewComment {
  mutes, err := GetMutedUsers(ctx, n.db, n.UserID, false)
  if err != nil {
	  return err
  }
  for _, m := range mutes {
	  if m.MutedUser.Username == n.Notif.(*NotificationNewComment).CommentAuthor {
		  return nil
	  }
  }
}
```

**Comment by reallytiredofclowns** [comment]
bff6c9b fixed this.
