### ISSUE TITLE
[BUG] Receiving notifications from muted users

### ISSUE THREAD

**Issue by noClaps** [discuitnet/discuit#89]
> You get notifications if muted users respond to your post or comment too. That definitely shouldn't be the case

[Originally reported by Amateurmetheus](https://discuit.net/DiscuitSuggestions/post/FMbjYcCx/17d2d57a895d52b4bcb0d78f)

**Comment by previnder** [comment]
Fixed in [bff6c9b](https://github.com/discuitnet/discuit/commit/bff6c9b88b8be6c9abcb435bb58c481cc6def8cf).
