### ISSUE TITLE
Code blocks should use a fixed-width font

### ISSUE THREAD

**Issue by reallytiredofclowns** [discuitnet/discuit#9]
Code blocks using the two common methods (fenced using triple backticks ``` or preceded by four spaces) currently render using a variable-width font, which messes up visual alignment when sharing code.

[Example here](https://discuit.net/test/post/YE40rD4Z). Note the one with the thin pipes | and thicker dashes -. I would expect them to line up perfectly one under the other in a code block.

**Comment by previnder** [comment]
I hadn't notice this before. Thanks for creating the issue.
