### ISSUE TITLE
[FEATURE] Lists improvements

### ISSUE THREAD

**Issue by noClaps** [discuitnet/discuit#90]
- [x] Have a link to the user's lists page on the user's profile. Currently there is no way to navigate to a user's list page without knowing and typing out the `/@users/lists` URL.
- [x] Allow creating lists from the lists page. The only way to create a list at the moment is during the save post/comment flow. There should be a way to create new, empty lists from the lists page.
- [x] Allow easily removing items from a lists without the additional steps of clicking on the `Save to list` menu item and then unchecking the list.
- [ ] Allow easily moving items from one list to another.

Original reported by JestJack in [this comment](https://discuit.net/general/post/V12FZQL8/17d2bb2e3a3ddb4fbb63a04c) and [this comment](https://discuit.net/general/post/V12FZQL8/17d2bc03acb27578a8618426).

**Comment by noClaps** [comment]
I've made them into a checklist in case they need to be separated out into individual issues.

**Comment by Kaamkiya** [comment]
This can be closed now, right?

**Comment by previnder** [comment]
Yeah, I think so. I'm not sure what @noClaps meant by the last item, but right now it's not that difficult to move an item from one list to another: click save, remove the tick on one list, and add the tick to another.

Closing.
